version: "3.9"
services:
  postgres:
    image: postgres:15
    container_name: postgres_local
    restart: always
    environment:
      POSTGRES_DB: projetcloud
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mamaika77
    ports:
      - "5432:5432"
    volumes:
      - ./base/base.sql:/docker-entrypoint-initdb.d/01_base.sql:ro
      - ./base/base_donnees.sql:/docker-entrypoint-initdb.d/02_base_donnees.sql:ro

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend_app
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/projetcloud
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: mamaika77
    ports:
      - "8080:8080"
    restart: always

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend_app
    depends_on:
      - backend
    ports:
      - "5173:80"
    restart: always

  tileserver:
    image: nginx:alpine
    container_name: tileserver
    ports:
      - "8081:80"
    volumes:
      - ./map-data/antananarivo/tiles:/usr/share/nginx/html/tiles:ro